# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Gists' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gists
  pod 'Alamofire'
  pod 'PINRemoteImage', '~> 2.1'
end
